spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: dev,configserver
    import: optional:configserver:http://localhost:8888
    cloud:
      config:
        fail-fast: true


server:
  port: 50000