spring:
  application:
      name: gateway-service
  config:
      activate:
          on-profile: dev,configserver
      import: optional:configserver:http://localhost:8888
  cloud:
      config:
          fail-fast: true
      gateway:
          routes:
              portfolio-server-url: lb://portfolio-service
              discovery-server-url: http://localhost:8761
  main:
    web-application-type: reactive

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
  lifetime: 1

server:
  port: 58089
  forward-headers-strategy: framework