spring:
  application:
      name: gateway-service
  profiles:
      active: dev
  config:
      activate:
          on-profile: dev
      import: optional:configserver:http://localhost:8888
      cloud:
          config:
              fail-fast: true

server:
  port: 58089
  forward-headers-strategy: framework