spring:
    application:
        name: price-service
    profiles:
        active: dev
    config:
        activate:
            on-profile: dev
        import: optional:configserver:http://localhost:8888
    cloud:
        config:
            fail-fast: true

server:
    port: 60000