spring:
  application:
    name: aggregator-service
  config:
    activate:
      on-profile: dev,configserver
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
  scheduler:
    enabled: true

nyse:
  personal:
    api-key: 3Q91ALMC4A07C0EX
  api-key: demo
  url: "https://www.alphavantage.co/query?function=LISTING_STATUS&apikey="

server:
  port: 8081